# Generated by Django 3.2 on 2022-07-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_add_email',
            new_name='is_ad_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_add_message',
            new_name='is_ad_message',
        ),
    ]
